// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(transponder_coreFFI)
import transponder_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_transponder_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_transponder_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureTransponderCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


/**
 * City information for reverse geocoding
 */
public struct City: Equatable, Hashable {
    public var name: String
    public var lat: Double
    public var lng: Double
    public var region: String
    public var country: String
    public var population: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, lat: Double, lng: Double, region: String, country: String, population: UInt32) {
        self.name = name
        self.lat = lat
        self.lng = lng
        self.region = region
        self.country = country
        self.population = population
    }

    
}

#if compiler(>=6)
extension City: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCity: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> City {
        return
            try City(
                name: FfiConverterString.read(from: &buf), 
                lat: FfiConverterDouble.read(from: &buf), 
                lng: FfiConverterDouble.read(from: &buf), 
                region: FfiConverterString.read(from: &buf), 
                country: FfiConverterString.read(from: &buf), 
                population: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: City, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterDouble.write(value.lat, into: &buf)
        FfiConverterDouble.write(value.lng, into: &buf)
        FfiConverterString.write(value.region, into: &buf)
        FfiConverterString.write(value.country, into: &buf)
        FfiConverterUInt32.write(value.population, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCity_lift(_ buf: RustBuffer) throws -> City {
    return try FfiConverterTypeCity.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCity_lower(_ value: City) -> RustBuffer {
    return FfiConverterTypeCity.lower(value)
}


/**
 * Result of fetching a friend's location
 */
public struct FetchedLocation: Equatable, Hashable {
    public var pubkey: String
    public var location: Location?
    public var updated: UInt64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(pubkey: String, location: Location?, updated: UInt64?) {
        self.pubkey = pubkey
        self.location = location
        self.updated = updated
    }

    
}

#if compiler(>=6)
extension FetchedLocation: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFetchedLocation: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FetchedLocation {
        return
            try FetchedLocation(
                pubkey: FfiConverterString.read(from: &buf), 
                location: FfiConverterOptionTypeLocation.read(from: &buf), 
                updated: FfiConverterOptionUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FetchedLocation, into buf: inout [UInt8]) {
        FfiConverterString.write(value.pubkey, into: &buf)
        FfiConverterOptionTypeLocation.write(value.location, into: &buf)
        FfiConverterOptionUInt64.write(value.updated, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFetchedLocation_lift(_ buf: RustBuffer) throws -> FetchedLocation {
    return try FfiConverterTypeFetchedLocation.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFetchedLocation_lower(_ value: FetchedLocation) -> RustBuffer {
    return FfiConverterTypeFetchedLocation.lower(value)
}


public struct Friend: Equatable, Hashable {
    public var pubkey: String
    public var server: String
    public var name: String
    public var shareWith: Bool
    public var fetchFrom: Bool
    public var location: Location?
    public var fetchedAt: UInt64?
    /**
     * Computed color for this friend's marker (hex string like "#4A90D9")
     * Not persisted - derived from pubkey on load
     */
    public var color: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(pubkey: String, server: String, name: String, shareWith: Bool, fetchFrom: Bool, location: Location?, fetchedAt: UInt64?, 
        /**
         * Computed color for this friend's marker (hex string like "#4A90D9")
         * Not persisted - derived from pubkey on load
         */color: String) {
        self.pubkey = pubkey
        self.server = server
        self.name = name
        self.shareWith = shareWith
        self.fetchFrom = fetchFrom
        self.location = location
        self.fetchedAt = fetchedAt
        self.color = color
    }

    
}

#if compiler(>=6)
extension Friend: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFriend: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Friend {
        return
            try Friend(
                pubkey: FfiConverterString.read(from: &buf), 
                server: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                shareWith: FfiConverterBool.read(from: &buf), 
                fetchFrom: FfiConverterBool.read(from: &buf), 
                location: FfiConverterOptionTypeLocation.read(from: &buf), 
                fetchedAt: FfiConverterOptionUInt64.read(from: &buf), 
                color: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Friend, into buf: inout [UInt8]) {
        FfiConverterString.write(value.pubkey, into: &buf)
        FfiConverterString.write(value.server, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterBool.write(value.shareWith, into: &buf)
        FfiConverterBool.write(value.fetchFrom, into: &buf)
        FfiConverterOptionTypeLocation.write(value.location, into: &buf)
        FfiConverterOptionUInt64.write(value.fetchedAt, into: &buf)
        FfiConverterString.write(value.color, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFriend_lift(_ buf: RustBuffer) throws -> Friend {
    return try FfiConverterTypeFriend.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFriend_lower(_ value: Friend) -> RustBuffer {
    return FfiConverterTypeFriend.lower(value)
}


public struct Identity: Equatable, Hashable {
    public var ed25519Private: Data
    public var ed25519Public: Data
    public var x25519Private: Data
    public var x25519Public: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(ed25519Private: Data, ed25519Public: Data, x25519Private: Data, x25519Public: Data) {
        self.ed25519Private = ed25519Private
        self.ed25519Public = ed25519Public
        self.x25519Private = x25519Private
        self.x25519Public = x25519Public
    }

    
}

#if compiler(>=6)
extension Identity: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIdentity: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Identity {
        return
            try Identity(
                ed25519Private: FfiConverterData.read(from: &buf), 
                ed25519Public: FfiConverterData.read(from: &buf), 
                x25519Private: FfiConverterData.read(from: &buf), 
                x25519Public: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: Identity, into buf: inout [UInt8]) {
        FfiConverterData.write(value.ed25519Private, into: &buf)
        FfiConverterData.write(value.ed25519Public, into: &buf)
        FfiConverterData.write(value.x25519Private, into: &buf)
        FfiConverterData.write(value.x25519Public, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIdentity_lift(_ buf: RustBuffer) throws -> Identity {
    return try FfiConverterTypeIdentity.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIdentity_lower(_ value: Identity) -> RustBuffer {
    return FfiConverterTypeIdentity.lower(value)
}


/**
 * License information grouped by license type
 */
public struct LicenseGroup: Equatable, Hashable {
    public var id: String
    public var name: String
    public var text: String
    public var packages: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, text: String, packages: [String]) {
        self.id = id
        self.name = name
        self.text = text
        self.packages = packages
    }

    
}

#if compiler(>=6)
extension LicenseGroup: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLicenseGroup: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LicenseGroup {
        return
            try LicenseGroup(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                text: FfiConverterString.read(from: &buf), 
                packages: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: LicenseGroup, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.text, into: &buf)
        FfiConverterSequenceString.write(value.packages, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLicenseGroup_lift(_ buf: RustBuffer) throws -> LicenseGroup {
    return try FfiConverterTypeLicenseGroup.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLicenseGroup_lower(_ value: LicenseGroup) -> RustBuffer {
    return FfiConverterTypeLicenseGroup.lower(value)
}


public struct Location: Equatable, Hashable {
    public var latitude: Double
    public var longitude: Double
    public var altitude: Double
    public var accuracy: Float
    public var timestamp: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(latitude: Double, longitude: Double, altitude: Double, accuracy: Float, timestamp: UInt64) {
        self.latitude = latitude
        self.longitude = longitude
        self.altitude = altitude
        self.accuracy = accuracy
        self.timestamp = timestamp
    }

    
}

#if compiler(>=6)
extension Location: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLocation: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Location {
        return
            try Location(
                latitude: FfiConverterDouble.read(from: &buf), 
                longitude: FfiConverterDouble.read(from: &buf), 
                altitude: FfiConverterDouble.read(from: &buf), 
                accuracy: FfiConverterFloat.read(from: &buf), 
                timestamp: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: Location, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.latitude, into: &buf)
        FfiConverterDouble.write(value.longitude, into: &buf)
        FfiConverterDouble.write(value.altitude, into: &buf)
        FfiConverterFloat.write(value.accuracy, into: &buf)
        FfiConverterUInt64.write(value.timestamp, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLocation_lift(_ buf: RustBuffer) throws -> Location {
    return try FfiConverterTypeLocation.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLocation_lower(_ value: Location) -> RustBuffer {
    return FfiConverterTypeLocation.lower(value)
}


/**
 * Parsed friend link data
 */
public struct ParsedFriendLink: Equatable, Hashable {
    public var pubkey: String
    public var server: String
    public var name: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(pubkey: String, server: String, name: String) {
        self.pubkey = pubkey
        self.server = server
        self.name = name
    }

    
}

#if compiler(>=6)
extension ParsedFriendLink: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeParsedFriendLink: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ParsedFriendLink {
        return
            try ParsedFriendLink(
                pubkey: FfiConverterString.read(from: &buf), 
                server: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ParsedFriendLink, into buf: inout [UInt8]) {
        FfiConverterString.write(value.pubkey, into: &buf)
        FfiConverterString.write(value.server, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeParsedFriendLink_lift(_ buf: RustBuffer) throws -> ParsedFriendLink {
    return try FfiConverterTypeParsedFriendLink.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeParsedFriendLink_lower(_ value: ParsedFriendLink) -> RustBuffer {
    return FfiConverterTypeParsedFriendLink.lower(value)
}


/**
 * HTTP request prepared by Rust core for native layer to execute
 */
public struct PreparedRequest: Equatable, Hashable {
    public var url: String
    public var method: String
    public var headers: [String: String]
    public var body: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(url: String, method: String, headers: [String: String], body: Data) {
        self.url = url
        self.method = method
        self.headers = headers
        self.body = body
    }

    
}

#if compiler(>=6)
extension PreparedRequest: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePreparedRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PreparedRequest {
        return
            try PreparedRequest(
                url: FfiConverterString.read(from: &buf), 
                method: FfiConverterString.read(from: &buf), 
                headers: FfiConverterDictionaryStringString.read(from: &buf), 
                body: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: PreparedRequest, into buf: inout [UInt8]) {
        FfiConverterString.write(value.url, into: &buf)
        FfiConverterString.write(value.method, into: &buf)
        FfiConverterDictionaryStringString.write(value.headers, into: &buf)
        FfiConverterData.write(value.body, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePreparedRequest_lift(_ buf: RustBuffer) throws -> PreparedRequest {
    return try FfiConverterTypePreparedRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePreparedRequest_lower(_ value: PreparedRequest) -> RustBuffer {
    return FfiConverterTypePreparedRequest.lower(value)
}


/**
 * Region lookup result
 */
public struct Region: Equatable, Hashable {
    public var name: String
    public var country: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, country: String) {
        self.name = name
        self.country = country
    }

    
}

#if compiler(>=6)
extension Region: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRegion: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Region {
        return
            try Region(
                name: FfiConverterString.read(from: &buf), 
                country: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Region, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.country, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRegion_lift(_ buf: RustBuffer) throws -> Region {
    return try FfiConverterTypeRegion.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRegion_lower(_ value: Region) -> RustBuffer {
    return FfiConverterTypeRegion.lower(value)
}


public enum CoreError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case InvalidKey
    case EncryptionFailed
    case DecryptionFailed
    case InvalidData
    case StorageNotInitialized
    case StorageError(details: String
    )
    case InvalidLink
    case FriendNotFound
    case StaleLocation

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension CoreError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCoreError: FfiConverterRustBuffer {
    typealias SwiftType = CoreError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CoreError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidKey
        case 2: return .EncryptionFailed
        case 3: return .DecryptionFailed
        case 4: return .InvalidData
        case 5: return .StorageNotInitialized
        case 6: return .StorageError(
            details: try FfiConverterString.read(from: &buf)
            )
        case 7: return .InvalidLink
        case 8: return .FriendNotFound
        case 9: return .StaleLocation

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CoreError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .InvalidKey:
            writeInt(&buf, Int32(1))
        
        
        case .EncryptionFailed:
            writeInt(&buf, Int32(2))
        
        
        case .DecryptionFailed:
            writeInt(&buf, Int32(3))
        
        
        case .InvalidData:
            writeInt(&buf, Int32(4))
        
        
        case .StorageNotInitialized:
            writeInt(&buf, Int32(5))
        
        
        case let .StorageError(details):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(details, into: &buf)
            
        
        case .InvalidLink:
            writeInt(&buf, Int32(7))
        
        
        case .FriendNotFound:
            writeInt(&buf, Int32(8))
        
        
        case .StaleLocation:
            writeInt(&buf, Int32(9))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreError_lift(_ buf: RustBuffer) throws -> CoreError {
    return try FfiConverterTypeCoreError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreError_lower(_ value: CoreError) -> RustBuffer {
    return FfiConverterTypeCoreError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionBool: FfiConverterRustBuffer {
    typealias SwiftType = Bool?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterBool.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterBool.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeCity: FfiConverterRustBuffer {
    typealias SwiftType = City?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeCity.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeCity.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeLocation: FfiConverterRustBuffer {
    typealias SwiftType = Location?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeLocation.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeLocation.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeRegion: FfiConverterRustBuffer {
    typealias SwiftType = Region?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeRegion.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeRegion.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFetchedLocation: FfiConverterRustBuffer {
    typealias SwiftType = [FetchedLocation]

    public static func write(_ value: [FetchedLocation], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFetchedLocation.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FetchedLocation] {
        let len: Int32 = try readInt(&buf)
        var seq = [FetchedLocation]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFetchedLocation.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFriend: FfiConverterRustBuffer {
    typealias SwiftType = [Friend]

    public static func write(_ value: [Friend], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFriend.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Friend] {
        let len: Int32 = try readInt(&buf)
        var seq = [Friend]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFriend.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeLicenseGroup: FfiConverterRustBuffer {
    typealias SwiftType = [LicenseGroup]

    public static func write(_ value: [LicenseGroup], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeLicenseGroup.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [LicenseGroup] {
        let len: Int32 = try readInt(&buf)
        var seq = [LicenseGroup]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeLicenseGroup.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypePreparedRequest: FfiConverterRustBuffer {
    typealias SwiftType = [PreparedRequest]

    public static func write(_ value: [PreparedRequest], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePreparedRequest.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PreparedRequest] {
        let len: Int32 = try readInt(&buf)
        var seq = [PreparedRequest]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePreparedRequest.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDictionaryStringString: FfiConverterRustBuffer {
    public static func write(_ value: [String: String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterString.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: String] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: String]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterString.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}
/**
 * Add a new friend. If a friend with the same pubkey exists, updates their info.
 */
public func addFriend(pubkey: String, server: String, name: String, shareWith: Bool, fetchFrom: Bool)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_transponder_core_fn_func_add_friend(
        FfiConverterString.lower(pubkey),
        FfiConverterString.lower(server),
        FfiConverterString.lower(name),
        FfiConverterBool.lower(shareWith),
        FfiConverterBool.lower(fetchFrom),$0
    )
}
}
/**
 * Derive a consistent color from a pubkey string.
 * Returns a hex color string like "#4A90D9".
 * Uses HSL with fixed saturation/lightness for good visibility.
 */
public func colorFromPubkey(pubkey: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_transponder_core_fn_func_color_from_pubkey(
        FfiConverterString.lower(pubkey),$0
    )
})
}
/**
 * Decrypt a multi-recipient blob using trial decryption
 * Format: version(1) | ephemeral(32) | count(2) | [nonce(12) | encrypted_dek(48)]... | data_nonce(12) | ciphertext
 * Returns the decrypted Location if we're a valid recipient
 */
public func decryptBlob(identity: Identity, blob: Data)throws  -> Location  {
    return try  FfiConverterTypeLocation_lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_transponder_core_fn_func_decrypt_blob(
        FfiConverterTypeIdentity_lower(identity),
        FfiConverterData.lower(blob),$0
    )
})
}
/**
 * Decrypt location data with AES-256-GCM using shared secret
 */
public func decryptLocation(encrypted: Data, sharedSecret: Data)throws  -> Location?  {
    return try  FfiConverterOptionTypeLocation.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_transponder_core_fn_func_decrypt_location(
        FfiConverterData.lower(encrypted),
        FfiConverterData.lower(sharedSecret),$0
    )
})
}
/**
 * Derive shared secret using X25519 ECDH
 */
public func deriveSharedSecret(myX25519Private: Data, theirX25519Public: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_transponder_core_fn_func_derive_shared_secret(
        FfiConverterData.lower(myX25519Private),
        FfiConverterData.lower(theirX25519Public),$0
    )
})
}
/**
 * Encrypt location data with AES-256-GCM using shared secret
 */
public func encryptLocation(location: Location, sharedSecret: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_transponder_core_fn_func_encrypt_location(
        FfiConverterTypeLocation_lower(location),
        FfiConverterData.lower(sharedSecret),$0
    )
})
}
/**
 * Find the nearest city to the given coordinates.
 * Uses a weighted score that prefers larger cities when distances are similar.
 */
public func findNearestCity(lat: Double, lng: Double) -> City?  {
    return try!  FfiConverterOptionTypeCity.lift(try! rustCall() {
    uniffi_transponder_core_fn_func_find_nearest_city(
        FfiConverterDouble.lower(lat),
        FfiConverterDouble.lower(lng),$0
    )
})
}
/**
 * Find the nearest city to the given coordinates, filtered by region.
 * First determines which region the coordinates are in, then only considers
 * cities in that region. Falls back to unfiltered search if no region match.
 */
public func findNearestCityInRegion(lat: Double, lng: Double) -> City?  {
    return try!  FfiConverterOptionTypeCity.lift(try! rustCall() {
    uniffi_transponder_core_fn_func_find_nearest_city_in_region(
        FfiConverterDouble.lower(lat),
        FfiConverterDouble.lower(lng),$0
    )
})
}
/**
 * Find which region contains the given coordinates using point-in-polygon tests.
 * Returns None if the point is not within any known region (e.g., ocean, coastal areas).
 */
public func findRegion(lat: Double, lng: Double) -> Region?  {
    return try!  FfiConverterOptionTypeRegion.lift(try! rustCall() {
    uniffi_transponder_core_fn_func_find_region(
        FfiConverterDouble.lower(lat),
        FfiConverterDouble.lower(lng),$0
    )
})
}
/**
 * Generate a friend link for sharing our identity
 * Format: coord://<server>/add/<pubkey>#<name>
 */
public func generateFriendLink(identity: Identity, server: String, name: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_transponder_core_fn_func_generate_friend_link(
        FfiConverterTypeIdentity_lower(identity),
        FfiConverterString.lower(server),
        FfiConverterString.lower(name),$0
    )
})
}
/**
 * Generate a new identity with Ed25519 (signing) and X25519 (key exchange) keypairs
 * X25519 keys are derived from Ed25519 for simplicity - only Ed25519 pubkey needed in friend links
 */
public func generateIdentity() -> Identity  {
    return try!  FfiConverterTypeIdentity_lift(try! rustCall() {
    uniffi_transponder_core_fn_func_generate_identity($0
    )
})
}
/**
 * Get friends to fetch location from (fetch_from == true)
 */
public func getFetchTargets() -> [Friend]  {
    return try!  FfiConverterSequenceTypeFriend.lift(try! rustCall() {
    uniffi_transponder_core_fn_func_get_fetch_targets($0
    )
})
}
/**
 * Get the color for an identity (what others see when viewing you)
 */
public func getIdentityColor(identity: Identity) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_transponder_core_fn_func_get_identity_color(
        FfiConverterTypeIdentity_lower(identity),$0
    )
})
}
/**
 * Get license information for all dependencies, grouped by license type
 */
public func getLicenses() -> [LicenseGroup]  {
    return try!  FfiConverterSequenceTypeLicenseGroup.lift(try! rustCall() {
    uniffi_transponder_core_fn_func_get_licenses($0
    )
})
}
/**
 * Get friends to share location with (share_with == true)
 */
public func getShareRecipients() -> [Friend]  {
    return try!  FfiConverterSequenceTypeFriend.lift(try! rustCall() {
    uniffi_transponder_core_fn_func_get_share_recipients($0
    )
})
}
/**
 * Get the version of the transponder core library
 */
public func getVersion() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_transponder_core_fn_func_get_version($0
    )
})
}
/**
 * Initialize storage with the app's data directory path.
 * Must be called once at app startup before any friend operations.
 */
public func initStorage(path: String)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_transponder_core_fn_func_init_storage(
        FfiConverterString.lower(path),$0
    )
}
}
/**
 * List all friends
 */
public func listFriends() -> [Friend]  {
    return try!  FfiConverterSequenceTypeFriend.lift(try! rustCall() {
    uniffi_transponder_core_fn_func_list_friends($0
    )
})
}
/**
 * Mark a location upload as successful, updating the last uploaded timestamp
 * Call this after successfully uploading a location to prevent re-uploading stale data
 */
public func markUploadSuccess(timestamp: UInt64)  {try! rustCall() {
    uniffi_transponder_core_fn_func_mark_upload_success(
        FfiConverterUInt64.lower(timestamp),$0
    )
}
}
/**
 * Migrate friend server URLs from old domain to new domain.
 * Returns the number of friends that were migrated.
 */
public func migrateServerUrls(fromDomain: String, toDomain: String)throws  -> UInt32  {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_transponder_core_fn_func_migrate_server_urls(
        FfiConverterString.lower(fromDomain),
        FfiConverterString.lower(toDomain),$0
    )
})
}
/**
 * Generate mock friends for development/testing.
 * Colors are computed automatically from pubkeys.
 */
public func mockFriends() -> [Friend]  {
    return try!  FfiConverterSequenceTypeFriend.lift(try! rustCall() {
    uniffi_transponder_core_fn_func_mock_friends($0
    )
})
}
/**
 * Parse a friend link into its components
 * Returns None if the link format is invalid
 */
public func parseFriendLink(url: String)throws  -> ParsedFriendLink  {
    return try  FfiConverterTypeParsedFriendLink_lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_transponder_core_fn_func_parse_friend_link(
        FfiConverterString.lower(url),$0
    )
})
}
/**
 * Prepare location fetch requests, grouped by server for federation
 * Returns one PreparedRequest per unique server
 */
public func prepareLocationFetch(friends: [Friend]) -> [PreparedRequest]  {
    return try!  FfiConverterSequenceTypePreparedRequest.lift(try! rustCall() {
    uniffi_transponder_core_fn_func_prepare_location_fetch(
        FfiConverterSequenceTypeFriend.lower(friends),$0
    )
})
}
/**
 * Prepare a location upload request for the native HTTP layer to execute
 * Returns StaleLocation error if the location timestamp is older than the last successful upload
 */
public func prepareLocationUpload(identity: Identity, location: Location, friends: [Friend], myServer: String)throws  -> PreparedRequest  {
    return try  FfiConverterTypePreparedRequest_lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_transponder_core_fn_func_prepare_location_upload(
        FfiConverterTypeIdentity_lower(identity),
        FfiConverterTypeLocation_lower(location),
        FfiConverterSequenceTypeFriend.lower(friends),
        FfiConverterString.lower(myServer),$0
    )
})
}
/**
 * Prepare a request to fetch our own location from the server
 * Used to verify what the server has stored for us
 */
public func prepareSelfLocationFetch(identity: Identity, server: String) -> PreparedRequest  {
    return try!  FfiConverterTypePreparedRequest_lift(try! rustCall() {
    uniffi_transponder_core_fn_func_prepare_self_location_fetch(
        FfiConverterTypeIdentity_lower(identity),
        FfiConverterString.lower(server),$0
    )
})
}
/**
 * Process a fetch response from the server and decrypt locations
 * Returns decrypted locations for each friend we can decrypt
 */
public func processFetchResponse(identity: Identity, responseBody: Data)throws  -> [FetchedLocation]  {
    return try  FfiConverterSequenceTypeFetchedLocation.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_transponder_core_fn_func_process_fetch_response(
        FfiConverterTypeIdentity_lower(identity),
        FfiConverterData.lower(responseBody),$0
    )
})
}
/**
 * Remove a friend by pubkey
 */
public func removeFriend(pubkey: String)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_transponder_core_fn_func_remove_friend(
        FfiConverterString.lower(pubkey),$0
    )
}
}
/**
 * Update an existing friend's settings
 */
public func updateFriend(pubkey: String, shareWith: Bool?, fetchFrom: Bool?, name: String?)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_transponder_core_fn_func_update_friend(
        FfiConverterString.lower(pubkey),
        FfiConverterOptionBool.lower(shareWith),
        FfiConverterOptionBool.lower(fetchFrom),
        FfiConverterOptionString.lower(name),$0
    )
}
}
/**
 * Update a friend's cached location after fetching
 */
public func updateFriendLocation(pubkey: String, location: Location?, fetchedAt: UInt64)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_transponder_core_fn_func_update_friend_location(
        FfiConverterString.lower(pubkey),
        FfiConverterOptionTypeLocation.lower(location),
        FfiConverterUInt64.lower(fetchedAt),$0
    )
}
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_transponder_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_transponder_core_checksum_func_add_friend() != 35250) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_color_from_pubkey() != 32599) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_decrypt_blob() != 43627) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_decrypt_location() != 50835) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_derive_shared_secret() != 64373) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_encrypt_location() != 17870) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_find_nearest_city() != 51288) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_find_nearest_city_in_region() != 24478) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_find_region() != 46428) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_generate_friend_link() != 59198) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_generate_identity() != 6989) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_get_fetch_targets() != 14783) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_get_identity_color() != 53474) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_get_licenses() != 45088) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_get_share_recipients() != 37891) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_get_version() != 46217) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_init_storage() != 55201) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_list_friends() != 45195) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_mark_upload_success() != 18730) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_migrate_server_urls() != 43548) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_mock_friends() != 8152) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_parse_friend_link() != 49766) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_prepare_location_fetch() != 12083) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_prepare_location_upload() != 54498) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_prepare_self_location_fetch() != 54555) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_process_fetch_response() != 6198) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_remove_friend() != 39913) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_update_friend() != 17618) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_transponder_core_checksum_func_update_friend_location() != 62428) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureTransponderCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all