// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.transponder_core

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_transponder_core_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.ffi_transponder_core_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Initial value and increment amount for handles. 
// These ensure that Kotlin-generated handles always have the lowest bit set
private const val UNIFFI_HANDLEMAP_INITIAL = 1.toLong()
private const val UNIFFI_HANDLEMAP_DELTA = 2.toLong()

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    // Start 
    private val counter = java.util.concurrent.atomic.AtomicLong(UNIFFI_HANDLEMAP_INITIAL)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(UNIFFI_HANDLEMAP_DELTA)
        map.put(handle, obj)
        return handle
    }

    // Clone a handle, creating a new one
    fun clone(handle: Long): Long {
        val obj = map.get(handle) ?: throw InternalException("UniffiHandleMap.clone: Invalid handle")
        return insert(obj)
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "transponder_core"
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureDroppedCallback : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceClone : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
    : Long
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFutureDroppedCallbackStruct(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureDroppedCallback? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureDroppedCallback? = null,
    ): UniffiForeignFutureDroppedCallbackStruct(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureDroppedCallbackStruct) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureResultVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultVoid.UniffiByValue,)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "transponder_core"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }
    external fun uniffi_transponder_core_checksum_func_add_friend(
    ): Short
    external fun uniffi_transponder_core_checksum_func_color_from_pubkey(
    ): Short
    external fun uniffi_transponder_core_checksum_func_decrypt_blob(
    ): Short
    external fun uniffi_transponder_core_checksum_func_decrypt_location(
    ): Short
    external fun uniffi_transponder_core_checksum_func_derive_shared_secret(
    ): Short
    external fun uniffi_transponder_core_checksum_func_encrypt_location(
    ): Short
    external fun uniffi_transponder_core_checksum_func_find_nearest_city(
    ): Short
    external fun uniffi_transponder_core_checksum_func_find_nearest_city_in_region(
    ): Short
    external fun uniffi_transponder_core_checksum_func_find_region(
    ): Short
    external fun uniffi_transponder_core_checksum_func_generate_friend_link(
    ): Short
    external fun uniffi_transponder_core_checksum_func_generate_identity(
    ): Short
    external fun uniffi_transponder_core_checksum_func_get_fetch_targets(
    ): Short
    external fun uniffi_transponder_core_checksum_func_get_identity_color(
    ): Short
    external fun uniffi_transponder_core_checksum_func_get_last_upload_timestamp(
    ): Short
    external fun uniffi_transponder_core_checksum_func_get_licenses(
    ): Short
    external fun uniffi_transponder_core_checksum_func_get_share_recipients(
    ): Short
    external fun uniffi_transponder_core_checksum_func_get_version(
    ): Short
    external fun uniffi_transponder_core_checksum_func_init_storage(
    ): Short
    external fun uniffi_transponder_core_checksum_func_list_friends(
    ): Short
    external fun uniffi_transponder_core_checksum_func_mark_upload_success(
    ): Short
    external fun uniffi_transponder_core_checksum_func_migrate_server_urls(
    ): Short
    external fun uniffi_transponder_core_checksum_func_mock_friends(
    ): Short
    external fun uniffi_transponder_core_checksum_func_parse_friend_link(
    ): Short
    external fun uniffi_transponder_core_checksum_func_prepare_location_fetch(
    ): Short
    external fun uniffi_transponder_core_checksum_func_prepare_location_upload(
    ): Short
    external fun uniffi_transponder_core_checksum_func_prepare_self_location_fetch(
    ): Short
    external fun uniffi_transponder_core_checksum_func_process_fetch_response(
    ): Short
    external fun uniffi_transponder_core_checksum_func_remove_friend(
    ): Short
    external fun uniffi_transponder_core_checksum_func_update_friend(
    ): Short
    external fun uniffi_transponder_core_checksum_func_update_friend_location(
    ): Short
    external fun ffi_transponder_core_uniffi_contract_version(
    ): Int
    
        
}

internal object UniffiLib {
    

    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "transponder_core"))
        
    }
    external fun uniffi_transponder_core_fn_func_add_friend(`pubkey`: RustBuffer.ByValue,`server`: RustBuffer.ByValue,`name`: RustBuffer.ByValue,`shareWith`: Byte,`fetchFrom`: Byte,uniffi_out_err: UniffiRustCallStatus, 
): Unit
external fun uniffi_transponder_core_fn_func_color_from_pubkey(`pubkey`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_transponder_core_fn_func_decrypt_blob(`identity`: RustBuffer.ByValue,`blob`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_transponder_core_fn_func_decrypt_location(`encrypted`: RustBuffer.ByValue,`sharedSecret`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_transponder_core_fn_func_derive_shared_secret(`myX25519Private`: RustBuffer.ByValue,`theirX25519Public`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_transponder_core_fn_func_encrypt_location(`location`: RustBuffer.ByValue,`sharedSecret`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_transponder_core_fn_func_find_nearest_city(`lat`: Double,`lng`: Double,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_transponder_core_fn_func_find_nearest_city_in_region(`lat`: Double,`lng`: Double,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_transponder_core_fn_func_find_region(`lat`: Double,`lng`: Double,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_transponder_core_fn_func_generate_friend_link(`identity`: RustBuffer.ByValue,`server`: RustBuffer.ByValue,`name`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_transponder_core_fn_func_generate_identity(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_transponder_core_fn_func_get_fetch_targets(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_transponder_core_fn_func_get_identity_color(`identity`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_transponder_core_fn_func_get_last_upload_timestamp(uniffi_out_err: UniffiRustCallStatus, 
): Long
external fun uniffi_transponder_core_fn_func_get_licenses(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_transponder_core_fn_func_get_share_recipients(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_transponder_core_fn_func_get_version(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_transponder_core_fn_func_init_storage(`path`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Unit
external fun uniffi_transponder_core_fn_func_list_friends(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_transponder_core_fn_func_mark_upload_success(`timestamp`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Unit
external fun uniffi_transponder_core_fn_func_migrate_server_urls(`fromDomain`: RustBuffer.ByValue,`toDomain`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Int
external fun uniffi_transponder_core_fn_func_mock_friends(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_transponder_core_fn_func_parse_friend_link(`url`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_transponder_core_fn_func_prepare_location_fetch(`friends`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_transponder_core_fn_func_prepare_location_upload(`identity`: RustBuffer.ByValue,`location`: RustBuffer.ByValue,`friends`: RustBuffer.ByValue,`myServer`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_transponder_core_fn_func_prepare_self_location_fetch(`identity`: RustBuffer.ByValue,`server`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_transponder_core_fn_func_process_fetch_response(`identity`: RustBuffer.ByValue,`responseBody`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_transponder_core_fn_func_remove_friend(`pubkey`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Unit
external fun uniffi_transponder_core_fn_func_update_friend(`pubkey`: RustBuffer.ByValue,`shareWith`: RustBuffer.ByValue,`fetchFrom`: RustBuffer.ByValue,`name`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Unit
external fun uniffi_transponder_core_fn_func_update_friend_location(`pubkey`: RustBuffer.ByValue,`location`: RustBuffer.ByValue,`fetchedAt`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Unit
external fun ffi_transponder_core_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun ffi_transponder_core_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun ffi_transponder_core_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Unit
external fun ffi_transponder_core_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun ffi_transponder_core_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_transponder_core_rust_future_cancel_u8(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_free_u8(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Byte
external fun ffi_transponder_core_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_transponder_core_rust_future_cancel_i8(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_free_i8(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Byte
external fun ffi_transponder_core_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_transponder_core_rust_future_cancel_u16(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_free_u16(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Short
external fun ffi_transponder_core_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_transponder_core_rust_future_cancel_i16(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_free_i16(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Short
external fun ffi_transponder_core_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_transponder_core_rust_future_cancel_u32(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_free_u32(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Int
external fun ffi_transponder_core_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_transponder_core_rust_future_cancel_i32(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_free_i32(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Int
external fun ffi_transponder_core_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_transponder_core_rust_future_cancel_u64(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_free_u64(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Long
external fun ffi_transponder_core_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_transponder_core_rust_future_cancel_i64(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_free_i64(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Long
external fun ffi_transponder_core_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_transponder_core_rust_future_cancel_f32(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_free_f32(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Float
external fun ffi_transponder_core_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_transponder_core_rust_future_cancel_f64(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_free_f64(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Double
external fun ffi_transponder_core_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_transponder_core_rust_future_cancel_rust_buffer(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_free_rust_buffer(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun ffi_transponder_core_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_transponder_core_rust_future_cancel_void(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_free_void(`handle`: Long,
): Unit
external fun ffi_transponder_core_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Unit

    
}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_transponder_core_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_transponder_core_checksum_func_add_friend() != 35250.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_color_from_pubkey() != 32599.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_decrypt_blob() != 43627.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_decrypt_location() != 50835.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_derive_shared_secret() != 64373.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_encrypt_location() != 17870.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_find_nearest_city() != 51288.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_find_nearest_city_in_region() != 24478.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_find_region() != 46428.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_generate_friend_link() != 59198.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_generate_identity() != 6989.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_get_fetch_targets() != 14783.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_get_identity_color() != 53474.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_get_last_upload_timestamp() != 4870.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_get_licenses() != 45088.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_get_share_recipients() != 37891.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_get_version() != 46217.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_init_storage() != 55201.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_list_friends() != 45195.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_mark_upload_success() != 18730.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_migrate_server_urls() != 43548.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_mock_friends() != 8152.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_parse_friend_link() != 49766.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_prepare_location_fetch() != 12083.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_prepare_location_upload() != 54498.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_prepare_self_location_fetch() != 54555.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_process_fetch_response() != 6198.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_remove_friend() != 39913.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_update_friend() != 17618.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_transponder_core_checksum_func_update_friend_location() != 62428.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    IntegrityCheckingUniffiLib
    // UniffiLib() initialized as objects are used, but we still need to explicitly
    // reference it so initialization across crates works as expected.
    UniffiLib
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Placeholder object used to signal that we're constructing an interface with a FFI handle.
 *
 * This is the first argument for interface constructors that input a raw handle. It exists is that
 * so we can avoid signature conflicts when an interface has a regular constructor than inputs a
 * Long.
 *
 * @suppress
 * */
object UniffiWithHandle

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoHandle

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterFloat: FfiConverter<Float, Float> {
    override fun lift(value: Float): Float {
        return value
    }

    override fun read(buf: ByteBuffer): Float {
        return buf.getFloat()
    }

    override fun lower(value: Float): Float {
        return value
    }

    override fun allocationSize(value: Float) = 4UL

    override fun write(value: Float, buf: ByteBuffer) {
        buf.putFloat(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterDouble: FfiConverter<Double, Double> {
    override fun lift(value: Double): Double {
        return value
    }

    override fun read(buf: ByteBuffer): Double {
        return buf.getDouble()
    }

    override fun lower(value: Double): Double {
        return value
    }

    override fun allocationSize(value: Double) = 8UL

    override fun write(value: Double, buf: ByteBuffer) {
        buf.putDouble(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

/**
 * @suppress
 */
public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): ULong {
        return 4UL + value.size.toULong()
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}



/**
 * City information for reverse geocoding
 */
data class City (
    var `name`: kotlin.String
    , 
    var `lat`: kotlin.Double
    , 
    var `lng`: kotlin.Double
    , 
    var `region`: kotlin.String
    , 
    var `country`: kotlin.String
    , 
    var `population`: kotlin.UInt
    
){
    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeCity: FfiConverterRustBuffer<City> {
    override fun read(buf: ByteBuffer): City {
        return City(
            FfiConverterString.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterUInt.read(buf),
        )
    }

    override fun allocationSize(value: City) = (
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterDouble.allocationSize(value.`lat`) +
            FfiConverterDouble.allocationSize(value.`lng`) +
            FfiConverterString.allocationSize(value.`region`) +
            FfiConverterString.allocationSize(value.`country`) +
            FfiConverterUInt.allocationSize(value.`population`)
    )

    override fun write(value: City, buf: ByteBuffer) {
            FfiConverterString.write(value.`name`, buf)
            FfiConverterDouble.write(value.`lat`, buf)
            FfiConverterDouble.write(value.`lng`, buf)
            FfiConverterString.write(value.`region`, buf)
            FfiConverterString.write(value.`country`, buf)
            FfiConverterUInt.write(value.`population`, buf)
    }
}



/**
 * Result of fetching a friend's location
 */
data class FetchedLocation (
    var `pubkey`: kotlin.String
    , 
    var `location`: Location?
    , 
    var `updated`: kotlin.ULong?
    
){
    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFetchedLocation: FfiConverterRustBuffer<FetchedLocation> {
    override fun read(buf: ByteBuffer): FetchedLocation {
        return FetchedLocation(
            FfiConverterString.read(buf),
            FfiConverterOptionalTypeLocation.read(buf),
            FfiConverterOptionalULong.read(buf),
        )
    }

    override fun allocationSize(value: FetchedLocation) = (
            FfiConverterString.allocationSize(value.`pubkey`) +
            FfiConverterOptionalTypeLocation.allocationSize(value.`location`) +
            FfiConverterOptionalULong.allocationSize(value.`updated`)
    )

    override fun write(value: FetchedLocation, buf: ByteBuffer) {
            FfiConverterString.write(value.`pubkey`, buf)
            FfiConverterOptionalTypeLocation.write(value.`location`, buf)
            FfiConverterOptionalULong.write(value.`updated`, buf)
    }
}



data class Friend (
    var `pubkey`: kotlin.String
    , 
    var `server`: kotlin.String
    , 
    var `name`: kotlin.String
    , 
    var `shareWith`: kotlin.Boolean
    , 
    var `fetchFrom`: kotlin.Boolean
    , 
    var `location`: Location?
    , 
    var `fetchedAt`: kotlin.ULong?
    , 
    /**
     * Computed color for this friend's marker (hex string like "#4A90D9")
     * Not persisted - derived from pubkey on load
     */
    var `color`: kotlin.String
    
){
    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFriend: FfiConverterRustBuffer<Friend> {
    override fun read(buf: ByteBuffer): Friend {
        return Friend(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterOptionalTypeLocation.read(buf),
            FfiConverterOptionalULong.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: Friend) = (
            FfiConverterString.allocationSize(value.`pubkey`) +
            FfiConverterString.allocationSize(value.`server`) +
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterBoolean.allocationSize(value.`shareWith`) +
            FfiConverterBoolean.allocationSize(value.`fetchFrom`) +
            FfiConverterOptionalTypeLocation.allocationSize(value.`location`) +
            FfiConverterOptionalULong.allocationSize(value.`fetchedAt`) +
            FfiConverterString.allocationSize(value.`color`)
    )

    override fun write(value: Friend, buf: ByteBuffer) {
            FfiConverterString.write(value.`pubkey`, buf)
            FfiConverterString.write(value.`server`, buf)
            FfiConverterString.write(value.`name`, buf)
            FfiConverterBoolean.write(value.`shareWith`, buf)
            FfiConverterBoolean.write(value.`fetchFrom`, buf)
            FfiConverterOptionalTypeLocation.write(value.`location`, buf)
            FfiConverterOptionalULong.write(value.`fetchedAt`, buf)
            FfiConverterString.write(value.`color`, buf)
    }
}



data class Identity (
    var `ed25519Private`: kotlin.ByteArray
    , 
    var `ed25519Public`: kotlin.ByteArray
    , 
    var `x25519Private`: kotlin.ByteArray
    , 
    var `x25519Public`: kotlin.ByteArray
    
){
    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeIdentity: FfiConverterRustBuffer<Identity> {
    override fun read(buf: ByteBuffer): Identity {
        return Identity(
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
        )
    }

    override fun allocationSize(value: Identity) = (
            FfiConverterByteArray.allocationSize(value.`ed25519Private`) +
            FfiConverterByteArray.allocationSize(value.`ed25519Public`) +
            FfiConverterByteArray.allocationSize(value.`x25519Private`) +
            FfiConverterByteArray.allocationSize(value.`x25519Public`)
    )

    override fun write(value: Identity, buf: ByteBuffer) {
            FfiConverterByteArray.write(value.`ed25519Private`, buf)
            FfiConverterByteArray.write(value.`ed25519Public`, buf)
            FfiConverterByteArray.write(value.`x25519Private`, buf)
            FfiConverterByteArray.write(value.`x25519Public`, buf)
    }
}



/**
 * License information grouped by license type
 */
data class LicenseGroup (
    var `id`: kotlin.String
    , 
    var `name`: kotlin.String
    , 
    var `text`: kotlin.String
    , 
    var `packages`: List<kotlin.String>
    
){
    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeLicenseGroup: FfiConverterRustBuffer<LicenseGroup> {
    override fun read(buf: ByteBuffer): LicenseGroup {
        return LicenseGroup(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterSequenceString.read(buf),
        )
    }

    override fun allocationSize(value: LicenseGroup) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterString.allocationSize(value.`text`) +
            FfiConverterSequenceString.allocationSize(value.`packages`)
    )

    override fun write(value: LicenseGroup, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`name`, buf)
            FfiConverterString.write(value.`text`, buf)
            FfiConverterSequenceString.write(value.`packages`, buf)
    }
}



data class Location (
    var `latitude`: kotlin.Double
    , 
    var `longitude`: kotlin.Double
    , 
    var `altitude`: kotlin.Double
    , 
    var `accuracy`: kotlin.Float
    , 
    var `timestamp`: kotlin.ULong
    
){
    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeLocation: FfiConverterRustBuffer<Location> {
    override fun read(buf: ByteBuffer): Location {
        return Location(
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterFloat.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: Location) = (
            FfiConverterDouble.allocationSize(value.`latitude`) +
            FfiConverterDouble.allocationSize(value.`longitude`) +
            FfiConverterDouble.allocationSize(value.`altitude`) +
            FfiConverterFloat.allocationSize(value.`accuracy`) +
            FfiConverterULong.allocationSize(value.`timestamp`)
    )

    override fun write(value: Location, buf: ByteBuffer) {
            FfiConverterDouble.write(value.`latitude`, buf)
            FfiConverterDouble.write(value.`longitude`, buf)
            FfiConverterDouble.write(value.`altitude`, buf)
            FfiConverterFloat.write(value.`accuracy`, buf)
            FfiConverterULong.write(value.`timestamp`, buf)
    }
}



/**
 * Parsed friend link data
 */
data class ParsedFriendLink (
    var `pubkey`: kotlin.String
    , 
    var `server`: kotlin.String
    , 
    var `name`: kotlin.String
    
){
    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeParsedFriendLink: FfiConverterRustBuffer<ParsedFriendLink> {
    override fun read(buf: ByteBuffer): ParsedFriendLink {
        return ParsedFriendLink(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: ParsedFriendLink) = (
            FfiConverterString.allocationSize(value.`pubkey`) +
            FfiConverterString.allocationSize(value.`server`) +
            FfiConverterString.allocationSize(value.`name`)
    )

    override fun write(value: ParsedFriendLink, buf: ByteBuffer) {
            FfiConverterString.write(value.`pubkey`, buf)
            FfiConverterString.write(value.`server`, buf)
            FfiConverterString.write(value.`name`, buf)
    }
}



/**
 * HTTP request prepared by Rust core for native layer to execute
 */
data class PreparedRequest (
    var `url`: kotlin.String
    , 
    var `method`: kotlin.String
    , 
    var `headers`: Map<kotlin.String, kotlin.String>
    , 
    var `body`: kotlin.ByteArray
    
){
    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypePreparedRequest: FfiConverterRustBuffer<PreparedRequest> {
    override fun read(buf: ByteBuffer): PreparedRequest {
        return PreparedRequest(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterMapStringString.read(buf),
            FfiConverterByteArray.read(buf),
        )
    }

    override fun allocationSize(value: PreparedRequest) = (
            FfiConverterString.allocationSize(value.`url`) +
            FfiConverterString.allocationSize(value.`method`) +
            FfiConverterMapStringString.allocationSize(value.`headers`) +
            FfiConverterByteArray.allocationSize(value.`body`)
    )

    override fun write(value: PreparedRequest, buf: ByteBuffer) {
            FfiConverterString.write(value.`url`, buf)
            FfiConverterString.write(value.`method`, buf)
            FfiConverterMapStringString.write(value.`headers`, buf)
            FfiConverterByteArray.write(value.`body`, buf)
    }
}



/**
 * Region lookup result
 */
data class Region (
    var `name`: kotlin.String
    , 
    var `country`: kotlin.String
    
){
    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeRegion: FfiConverterRustBuffer<Region> {
    override fun read(buf: ByteBuffer): Region {
        return Region(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: Region) = (
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterString.allocationSize(value.`country`)
    )

    override fun write(value: Region, buf: ByteBuffer) {
            FfiConverterString.write(value.`name`, buf)
            FfiConverterString.write(value.`country`, buf)
    }
}





sealed class CoreException: kotlin.Exception() {
    
    class InvalidKey(
        ) : CoreException() {
        override val message
            get() = ""
    }
    
    class EncryptionFailed(
        ) : CoreException() {
        override val message
            get() = ""
    }
    
    class DecryptionFailed(
        ) : CoreException() {
        override val message
            get() = ""
    }
    
    class InvalidData(
        ) : CoreException() {
        override val message
            get() = ""
    }
    
    class StorageNotInitialized(
        ) : CoreException() {
        override val message
            get() = ""
    }
    
    class StorageException(
        
        val `details`: kotlin.String
        ) : CoreException() {
        override val message
            get() = "details=${ `details` }"
    }
    
    class InvalidLink(
        ) : CoreException() {
        override val message
            get() = ""
    }
    
    class FriendNotFound(
        ) : CoreException() {
        override val message
            get() = ""
    }
    
    class StaleLocation(
        ) : CoreException() {
        override val message
            get() = ""
    }
    

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<CoreException> {
        override fun lift(error_buf: RustBuffer.ByValue): CoreException = FfiConverterTypeCoreError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeCoreError : FfiConverterRustBuffer<CoreException> {
    override fun read(buf: ByteBuffer): CoreException {
        

        return when(buf.getInt()) {
            1 -> CoreException.InvalidKey()
            2 -> CoreException.EncryptionFailed()
            3 -> CoreException.DecryptionFailed()
            4 -> CoreException.InvalidData()
            5 -> CoreException.StorageNotInitialized()
            6 -> CoreException.StorageException(
                FfiConverterString.read(buf),
                )
            7 -> CoreException.InvalidLink()
            8 -> CoreException.FriendNotFound()
            9 -> CoreException.StaleLocation()
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: CoreException): ULong {
        return when(value) {
            is CoreException.InvalidKey -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is CoreException.EncryptionFailed -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is CoreException.DecryptionFailed -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is CoreException.InvalidData -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is CoreException.StorageNotInitialized -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is CoreException.StorageException -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`details`)
            )
            is CoreException.InvalidLink -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is CoreException.FriendNotFound -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is CoreException.StaleLocation -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
        }
    }

    override fun write(value: CoreException, buf: ByteBuffer) {
        when(value) {
            is CoreException.InvalidKey -> {
                buf.putInt(1)
                Unit
            }
            is CoreException.EncryptionFailed -> {
                buf.putInt(2)
                Unit
            }
            is CoreException.DecryptionFailed -> {
                buf.putInt(3)
                Unit
            }
            is CoreException.InvalidData -> {
                buf.putInt(4)
                Unit
            }
            is CoreException.StorageNotInitialized -> {
                buf.putInt(5)
                Unit
            }
            is CoreException.StorageException -> {
                buf.putInt(6)
                FfiConverterString.write(value.`details`, buf)
                Unit
            }
            is CoreException.InvalidLink -> {
                buf.putInt(7)
                Unit
            }
            is CoreException.FriendNotFound -> {
                buf.putInt(8)
                Unit
            }
            is CoreException.StaleLocation -> {
                buf.putInt(9)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




/**
 * @suppress
 */
public object FfiConverterOptionalULong: FfiConverterRustBuffer<kotlin.ULong?> {
    override fun read(buf: ByteBuffer): kotlin.ULong? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterULong.read(buf)
    }

    override fun allocationSize(value: kotlin.ULong?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterULong.allocationSize(value)
        }
    }

    override fun write(value: kotlin.ULong?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterULong.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalBoolean: FfiConverterRustBuffer<kotlin.Boolean?> {
    override fun read(buf: ByteBuffer): kotlin.Boolean? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterBoolean.read(buf)
    }

    override fun allocationSize(value: kotlin.Boolean?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterBoolean.allocationSize(value)
        }
    }

    override fun write(value: kotlin.Boolean?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterBoolean.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeCity: FfiConverterRustBuffer<City?> {
    override fun read(buf: ByteBuffer): City? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeCity.read(buf)
    }

    override fun allocationSize(value: City?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeCity.allocationSize(value)
        }
    }

    override fun write(value: City?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeCity.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeLocation: FfiConverterRustBuffer<Location?> {
    override fun read(buf: ByteBuffer): Location? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeLocation.read(buf)
    }

    override fun allocationSize(value: Location?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeLocation.allocationSize(value)
        }
    }

    override fun write(value: Location?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeLocation.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeRegion: FfiConverterRustBuffer<Region?> {
    override fun read(buf: ByteBuffer): Region? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeRegion.read(buf)
    }

    override fun allocationSize(value: Region?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeRegion.allocationSize(value)
        }
    }

    override fun write(value: Region?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeRegion.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFetchedLocation: FfiConverterRustBuffer<List<FetchedLocation>> {
    override fun read(buf: ByteBuffer): List<FetchedLocation> {
        val len = buf.getInt()
        return List<FetchedLocation>(len) {
            FfiConverterTypeFetchedLocation.read(buf)
        }
    }

    override fun allocationSize(value: List<FetchedLocation>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFetchedLocation.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FetchedLocation>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFetchedLocation.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFriend: FfiConverterRustBuffer<List<Friend>> {
    override fun read(buf: ByteBuffer): List<Friend> {
        val len = buf.getInt()
        return List<Friend>(len) {
            FfiConverterTypeFriend.read(buf)
        }
    }

    override fun allocationSize(value: List<Friend>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFriend.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<Friend>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFriend.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeLicenseGroup: FfiConverterRustBuffer<List<LicenseGroup>> {
    override fun read(buf: ByteBuffer): List<LicenseGroup> {
        val len = buf.getInt()
        return List<LicenseGroup>(len) {
            FfiConverterTypeLicenseGroup.read(buf)
        }
    }

    override fun allocationSize(value: List<LicenseGroup>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeLicenseGroup.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<LicenseGroup>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeLicenseGroup.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypePreparedRequest: FfiConverterRustBuffer<List<PreparedRequest>> {
    override fun read(buf: ByteBuffer): List<PreparedRequest> {
        val len = buf.getInt()
        return List<PreparedRequest>(len) {
            FfiConverterTypePreparedRequest.read(buf)
        }
    }

    override fun allocationSize(value: List<PreparedRequest>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypePreparedRequest.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<PreparedRequest>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypePreparedRequest.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterMapStringString: FfiConverterRustBuffer<Map<kotlin.String, kotlin.String>> {
    override fun read(buf: ByteBuffer): Map<kotlin.String, kotlin.String> {
        val len = buf.getInt()
        return buildMap<kotlin.String, kotlin.String>(len) {
            repeat(len) {
                val k = FfiConverterString.read(buf)
                val v = FfiConverterString.read(buf)
                this[k] = v
            }
        }
    }

    override fun allocationSize(value: Map<kotlin.String, kotlin.String>): ULong {
        val spaceForMapSize = 4UL
        val spaceForChildren = value.map { (k, v) ->
            FfiConverterString.allocationSize(k) +
            FfiConverterString.allocationSize(v)
        }.sum()
        return spaceForMapSize + spaceForChildren
    }

    override fun write(value: Map<kotlin.String, kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        // The parens on `(k, v)` here ensure we're calling the right method,
        // which is important for compatibility with older android devices.
        // Ref https://blog.danlew.net/2017/03/16/kotlin-puzzler-whose-line-is-it-anyways/
        value.forEach { (k, v) ->
            FfiConverterString.write(k, buf)
            FfiConverterString.write(v, buf)
        }
    }
}
        /**
         * Add a new friend. If a friend with the same pubkey exists, updates their info.
         */
    @Throws(CoreException::class) fun `addFriend`(`pubkey`: kotlin.String, `server`: kotlin.String, `name`: kotlin.String, `shareWith`: kotlin.Boolean, `fetchFrom`: kotlin.Boolean)
        = 
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_add_friend(
    
        FfiConverterString.lower(`pubkey`),FfiConverterString.lower(`server`),FfiConverterString.lower(`name`),FfiConverterBoolean.lower(`shareWith`),FfiConverterBoolean.lower(`fetchFrom`),_status)
}
    
    

        /**
         * Derive a consistent color from a pubkey string.
         * Returns a hex color string like "#4A90D9".
         * Uses HSL with fixed saturation/lightness for good visibility.
         */ fun `colorFromPubkey`(`pubkey`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_color_from_pubkey(
    
        FfiConverterString.lower(`pubkey`),_status)
}
    )
    }
    

        /**
         * Decrypt a multi-recipient blob using trial decryption
         * Format: version(1) | ephemeral(32) | count(2) | [nonce(12) | encrypted_dek(48)]... | data_nonce(12) | ciphertext
         * Returns the decrypted Location if we're a valid recipient
         */
    @Throws(CoreException::class) fun `decryptBlob`(`identity`: Identity, `blob`: kotlin.ByteArray): Location {
            return FfiConverterTypeLocation.lift(
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_decrypt_blob(
    
        FfiConverterTypeIdentity.lower(`identity`),FfiConverterByteArray.lower(`blob`),_status)
}
    )
    }
    

        /**
         * Decrypt location data with AES-256-GCM using shared secret
         */
    @Throws(CoreException::class) fun `decryptLocation`(`encrypted`: kotlin.ByteArray, `sharedSecret`: kotlin.ByteArray): Location? {
            return FfiConverterOptionalTypeLocation.lift(
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_decrypt_location(
    
        FfiConverterByteArray.lower(`encrypted`),FfiConverterByteArray.lower(`sharedSecret`),_status)
}
    )
    }
    

        /**
         * Derive shared secret using X25519 ECDH
         */
    @Throws(CoreException::class) fun `deriveSharedSecret`(`myX25519Private`: kotlin.ByteArray, `theirX25519Public`: kotlin.ByteArray): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_derive_shared_secret(
    
        FfiConverterByteArray.lower(`myX25519Private`),FfiConverterByteArray.lower(`theirX25519Public`),_status)
}
    )
    }
    

        /**
         * Encrypt location data with AES-256-GCM using shared secret
         */
    @Throws(CoreException::class) fun `encryptLocation`(`location`: Location, `sharedSecret`: kotlin.ByteArray): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_encrypt_location(
    
        FfiConverterTypeLocation.lower(`location`),FfiConverterByteArray.lower(`sharedSecret`),_status)
}
    )
    }
    

        /**
         * Find the nearest city to the given coordinates.
         * Uses a weighted score that prefers larger cities when distances are similar.
         */ fun `findNearestCity`(`lat`: kotlin.Double, `lng`: kotlin.Double): City? {
            return FfiConverterOptionalTypeCity.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_find_nearest_city(
    
        FfiConverterDouble.lower(`lat`),FfiConverterDouble.lower(`lng`),_status)
}
    )
    }
    

        /**
         * Find the nearest city to the given coordinates, filtered by region.
         * First determines which region the coordinates are in, then only considers
         * cities in that region. Falls back to unfiltered search if no region match.
         */ fun `findNearestCityInRegion`(`lat`: kotlin.Double, `lng`: kotlin.Double): City? {
            return FfiConverterOptionalTypeCity.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_find_nearest_city_in_region(
    
        FfiConverterDouble.lower(`lat`),FfiConverterDouble.lower(`lng`),_status)
}
    )
    }
    

        /**
         * Find which region contains the given coordinates using point-in-polygon tests.
         * Returns None if the point is not within any known region (e.g., ocean, coastal areas).
         */ fun `findRegion`(`lat`: kotlin.Double, `lng`: kotlin.Double): Region? {
            return FfiConverterOptionalTypeRegion.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_find_region(
    
        FfiConverterDouble.lower(`lat`),FfiConverterDouble.lower(`lng`),_status)
}
    )
    }
    

        /**
         * Generate a friend link for sharing our identity
         * Format: coord://<server>/add/<pubkey>#<name>
         */ fun `generateFriendLink`(`identity`: Identity, `server`: kotlin.String, `name`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_generate_friend_link(
    
        FfiConverterTypeIdentity.lower(`identity`),FfiConverterString.lower(`server`),FfiConverterString.lower(`name`),_status)
}
    )
    }
    

        /**
         * Generate a new identity with Ed25519 (signing) and X25519 (key exchange) keypairs
         * X25519 keys are derived from Ed25519 for simplicity - only Ed25519 pubkey needed in friend links
         */ fun `generateIdentity`(): Identity {
            return FfiConverterTypeIdentity.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_generate_identity(
    
        _status)
}
    )
    }
    

        /**
         * Get friends to fetch location from (fetch_from == true)
         */ fun `getFetchTargets`(): List<Friend> {
            return FfiConverterSequenceTypeFriend.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_get_fetch_targets(
    
        _status)
}
    )
    }
    

        /**
         * Get the color for an identity (what others see when viewing you)
         */ fun `getIdentityColor`(`identity`: Identity): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_get_identity_color(
    
        FfiConverterTypeIdentity.lower(`identity`),_status)
}
    )
    }
    

        /**
         * Last successful upload timestamp (ms epoch), or 0 if never uploaded.
         */ fun `getLastUploadTimestamp`(): kotlin.ULong {
            return FfiConverterULong.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_get_last_upload_timestamp(
    
        _status)
}
    )
    }
    

        /**
         * Get license information for all dependencies, grouped by license type
         */ fun `getLicenses`(): List<LicenseGroup> {
            return FfiConverterSequenceTypeLicenseGroup.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_get_licenses(
    
        _status)
}
    )
    }
    

        /**
         * Get friends to share location with (share_with == true)
         */ fun `getShareRecipients`(): List<Friend> {
            return FfiConverterSequenceTypeFriend.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_get_share_recipients(
    
        _status)
}
    )
    }
    

        /**
         * Get the version of the transponder core library
         */ fun `getVersion`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_get_version(
    
        _status)
}
    )
    }
    

        /**
         * Initialize storage with the app's data directory path.
         * Must be called once at app startup before any friend operations.
         */
    @Throws(CoreException::class) fun `initStorage`(`path`: kotlin.String)
        = 
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_init_storage(
    
        FfiConverterString.lower(`path`),_status)
}
    
    

        /**
         * List all friends
         */ fun `listFriends`(): List<Friend> {
            return FfiConverterSequenceTypeFriend.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_list_friends(
    
        _status)
}
    )
    }
    

        /**
         * Mark a location upload as successful, updating the last uploaded timestamp
         * Call this after successfully uploading a location to prevent re-uploading stale data
         */ fun `markUploadSuccess`(`timestamp`: kotlin.ULong)
        = 
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_mark_upload_success(
    
        FfiConverterULong.lower(`timestamp`),_status)
}
    
    

        /**
         * Migrate friend server URLs from old domain to new domain.
         * Returns the number of friends that were migrated.
         */
    @Throws(CoreException::class) fun `migrateServerUrls`(`fromDomain`: kotlin.String, `toDomain`: kotlin.String): kotlin.UInt {
            return FfiConverterUInt.lift(
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_migrate_server_urls(
    
        FfiConverterString.lower(`fromDomain`),FfiConverterString.lower(`toDomain`),_status)
}
    )
    }
    

        /**
         * Generate mock friends for development/testing.
         * Colors are computed automatically from pubkeys.
         */ fun `mockFriends`(): List<Friend> {
            return FfiConverterSequenceTypeFriend.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_mock_friends(
    
        _status)
}
    )
    }
    

        /**
         * Parse a friend link into its components
         * Returns None if the link format is invalid
         */
    @Throws(CoreException::class) fun `parseFriendLink`(`url`: kotlin.String): ParsedFriendLink {
            return FfiConverterTypeParsedFriendLink.lift(
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_parse_friend_link(
    
        FfiConverterString.lower(`url`),_status)
}
    )
    }
    

        /**
         * Prepare location fetch requests, grouped by server for federation
         * Returns one PreparedRequest per unique server
         */ fun `prepareLocationFetch`(`friends`: List<Friend>): List<PreparedRequest> {
            return FfiConverterSequenceTypePreparedRequest.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_prepare_location_fetch(
    
        FfiConverterSequenceTypeFriend.lower(`friends`),_status)
}
    )
    }
    

        /**
         * Prepare a location upload request for the native HTTP layer to execute
         * Returns StaleLocation error if the location timestamp is older than the last successful upload
         */
    @Throws(CoreException::class) fun `prepareLocationUpload`(`identity`: Identity, `location`: Location, `friends`: List<Friend>, `myServer`: kotlin.String): PreparedRequest {
            return FfiConverterTypePreparedRequest.lift(
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_prepare_location_upload(
    
        FfiConverterTypeIdentity.lower(`identity`),FfiConverterTypeLocation.lower(`location`),FfiConverterSequenceTypeFriend.lower(`friends`),FfiConverterString.lower(`myServer`),_status)
}
    )
    }
    

        /**
         * Prepare a request to fetch our own location from the server
         * Used to verify what the server has stored for us
         */ fun `prepareSelfLocationFetch`(`identity`: Identity, `server`: kotlin.String): PreparedRequest {
            return FfiConverterTypePreparedRequest.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_prepare_self_location_fetch(
    
        FfiConverterTypeIdentity.lower(`identity`),FfiConverterString.lower(`server`),_status)
}
    )
    }
    

        /**
         * Process a fetch response from the server and decrypt locations
         * Returns decrypted locations for each friend we can decrypt
         */
    @Throws(CoreException::class) fun `processFetchResponse`(`identity`: Identity, `responseBody`: kotlin.ByteArray): List<FetchedLocation> {
            return FfiConverterSequenceTypeFetchedLocation.lift(
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_process_fetch_response(
    
        FfiConverterTypeIdentity.lower(`identity`),FfiConverterByteArray.lower(`responseBody`),_status)
}
    )
    }
    

        /**
         * Remove a friend by pubkey
         */
    @Throws(CoreException::class) fun `removeFriend`(`pubkey`: kotlin.String)
        = 
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_remove_friend(
    
        FfiConverterString.lower(`pubkey`),_status)
}
    
    

        /**
         * Update an existing friend's settings
         */
    @Throws(CoreException::class) fun `updateFriend`(`pubkey`: kotlin.String, `shareWith`: kotlin.Boolean?, `fetchFrom`: kotlin.Boolean?, `name`: kotlin.String?)
        = 
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_update_friend(
    
        FfiConverterString.lower(`pubkey`),FfiConverterOptionalBoolean.lower(`shareWith`),FfiConverterOptionalBoolean.lower(`fetchFrom`),FfiConverterOptionalString.lower(`name`),_status)
}
    
    

        /**
         * Update a friend's cached location after fetching
         */
    @Throws(CoreException::class) fun `updateFriendLocation`(`pubkey`: kotlin.String, `location`: Location?, `fetchedAt`: kotlin.ULong)
        = 
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.uniffi_transponder_core_fn_func_update_friend_location(
    
        FfiConverterString.lower(`pubkey`),FfiConverterOptionalTypeLocation.lower(`location`),FfiConverterULong.lower(`fetchedAt`),_status)
}
    
    


